name: Github Actions
on:
  push: 
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  ci-init:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest]
        node-version: [ 16.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install modules
        run: npm ci
      - name: Build project 
        run: npm run build
      - name: Check unit tests
        run: npm run test
      - name: Install chromium
        run: npx playwright install --with-deps chromium
      - name: Check e2e tests
        run: npm run e2e
     