name: Release Workflow
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy: 
      matrix:
        os: [ubuntu-latest]
        node-version: [ 16.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm ci

      - name: Get previous release tag
        id: previous_release
        run: |
          git fetch --tags
          git describe --tags --abbrev=0 --match="v*" > previous_release_tag.txt

      - name: Generate changelog
        id: changelog
        run: |
          git log $(cat previous_release_tag.txt)..HEAD --pretty=format:"- %s%n" > changelog.txt

      - name: Create or update release issue
        id: create_release_issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          token: ${{ secrets.SECRET_TOKEN }}
          title: Release ${{ github.ref }}
          body: |
            Changelog:
            $(cat changelog.txt)
          labels: RELEASE

      - name: Run unit tests
        run: npm run test-ci
    
      - name: Install chromium
        run: npx playwright install --with-deps chromium

      - name: Run e2e tests
        run: npm run e2e

      - name: Build project 
        run: npm run build

      - name: Archive project
        uses: actions/upload-artifact@v2
        with:
          name: project-artifact
          path: build

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: project-artifact
          path: build

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          git config --global user.name "SergeyEzhin"
          git config --global user.email "ezhin@mail.ru"
          git checkout --orphan gh-pages
          git --work-tree build add --all
          git --work-tree build commit -m "Publish to GitHub Pages"
          git push --force origin gh-pages

      - name: Add result link to release issue
        if: success()
        run: |
          echo "Test results: ./test-report.html" >> "$(cat create_release_issue.issue_path)"

      - name: Close release issue
        if: success()
        uses: peter-evans/close-issue@v3
        with:
          token: ${{ secrets.SECRET_TOKEN }}
          issue-number: ${{ steps.create_release_issue.outputs.issue-number }}
